classDiagram
    Dish <|-- CheeseBurger
    Dish <|-- Salad
    Dish <|-- Brownie
    AllergenGluten <|.. CheeseBurger
    AllergenGluten <|.. Brownie
    AllergenNuts <|.. Brownie
    Customer *-- Order
    Dish --* Order

    class Dish {
        +constructor(ingredients: string[])
        +showIngredients() string
        +showPrice() number
    }
    class CheeseBurger {
        +showPrice() number
    }
    class Salad {
        +showPrice() number
    }
    class Brownie {
        +showPrice() number
    }
    class AllergenGluten {
        +hasGluten() boolean
    }
    class AllergenNuts {
        +hasNuts() boolean
    }
    class DishFactory {
        +createDish(type: string, ingredients: string[]): Dish
    }

    class Customer {
        +constructor(name: string)
        +getname() string
        +createOrder() Order
        +addDishToOrder(dish: Dish): void
        +removeDishFromOrder(dish: Dish): void
        +getOrderTotalPrice() number
    }
    class Order {
        +constructor(customer: Customer, dishes: Dish[])
        +addDish(dish: Dish): void
        +removeDish(dish: Dish): void
        +getTotalPrice() number
        +addObserver(observer: Observer): void
        +removeObserver(observer: Observer): void
        +notifyObservers(): void
        +update(order: Order): void
    }
    class OrderFactory {
        +createOrder(customer: Customer): Order
    }
    class CustomerFactory {
        +createCustomer(name: string): Customer
    }
    class UpdateOrderStatus {
        +updateStatus(order: Order, status: OrderStatusEnum): void
    }
    class Kitchen {
        +update(order: Order): string
    }